[functions]
    directory = "functions/"
	
[[headers]]
for = "/*.br"
  [headers.values]
  Content-Encoding = "br"

[[headers]]
for = "/*.wasm.br"
  [headers.values]
  Content-Type = "application/wasm"
  
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type"
